### ISSUE TITLE
Bug fichier SQL

### ISSUE THREAD

**Issue by Tectore** [Mattox0/Fenrir#1]
Bonjour je voudrais tester votre bot mais je pense que le fichier SQL a un petit souci 

Il m'est impossible sur phpmyadmin de l'upload 

j'ai remarquer qu'il y avait des erreurs aussi

Vous avez mis AUTOINCREMENT au lieu de AUTO_INCREMENT

Et quand je corrige le fichier j'ai une autre erreur qui est celle-ci

Voila ce que j'ai fait :

```
CREATE TABLE `anniversaires` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`user_id` VARCHAR(255),
	`date` VARCHAR(255),
	`guild_id` VARCHAR(255),
	FOREIGN KEY (guild_id) REFERENCES servers(anniv_id)
);
```

à la place de 

```
CREATE TABLE anniversaires (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id VARCHAR(255),
	date VARCHAR(255),
	guild_id VARCHAR(255),
	FOREIGN KEY (guild_id) REFERENCES servers(anniv_id)
);
```

Mais j'ai l'erreur MySQL : #1215 - Impossible d'ajouter des contraintes d'index externe

**Comment by Mattox0** [comment]
Salut ! 

Effectivement j'avais fait pas mal de modifications entre temps, et je viens de changer le script SQL, donc tu peux tester et me dire si ça marche, car ça marche de mon côté !

Il se pourrait qu'il y est quelques beug côté bot et site, car les deux sont encore en cours de développement.

Je reste à ta disposition pour toute question.
